# Generated by Django 5.2.12 on 2026-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operation_equipment_run_per_piece_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='equipment_run_per_piece',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='equipment_setup_per_lot',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='labor_run_per_piece',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='labor_setup_per_lot',
            field=models.FloatField(default=0),
        ),
    ]
