# Generated by Django 5.2.12 on 2026-05-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipmentgroup_unique_equipment_group_per_org_and_more'),
        ('labor', '0002_remove_labor_unique_labor_name_per_org_labor_model_and_more'),
        ('operations', '0004_operation_advanced_time_fields'),
        ('organizations', '0001_initial'),
        ('products', '0002_remove_product_unique_product_per_org_product_model_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='unique_operation_per_product',
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'op_number'), name='unique_operation_per_product'),
        ),
    ]
